site_name: OOP notes
nav:
  - Home: README.md
  - oop1: oop1.md
  - oop2: oop2.md
  - oop3: oop3.md
  - oop4: oop4.md
  - oop5: oop5.md
  - oop6: oop6.md
  - oop7: oop7.md
  - oop8: oop8.md
theme:
  palette:
    - scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
    - scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
      primary: teal
      accent: purple
  font:
    text: Vazir
    code: Fira Code
  name: readthedocs
  language: fa
  features:
    - content.tabs
    - content.code.annotate
    - content.tooltips
    - navigation.top
    - navigation.expand
    - navigation.full
